class NewOrder():
        BlpCode = ""
        RicCode = ""
        ISINCode = ""
        SEDOLCode = ""
        ExchangeCode = ""
        BuySell = ""
        OrderPriceType = ""
        TotalQuantity = ""
        QuantityFilled = ""
        OrderStatus = ""
        LimitPrice = ""
        GrossFilledPrice = ""
        EnteredDateTime = ""
        LastExecutionDateTime = ""
        MarketID = ""
        Currency = ""
        OrderId = ""
        ParentOrderId = ""
        